"""empty message

Revision ID: 5ecce2b142f7
Revises: 
Create Date: 2025-01-03 18:16:07.537915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecce2b142f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_trip', sa.String(length=120), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('time_start', sa.String(length=100), nullable=False),
    sa.Column('time_end', sa.String(length=100), nullable=False),
    sa.Column('date_trip', sa.String(length=100), nullable=False),
    sa.Column('location_start', sa.String(length=100), nullable=False),
    sa.Column('location_end', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('rif', sa.String(length=100), nullable=False),
    sa.Column('description_company', sa.String(length=100), nullable=False),
    sa.Column('phone_company', sa.String(length=100), nullable=False),
    sa.Column('instagram_company', sa.String(length=100), nullable=False),
    sa.Column('facebook_company', sa.String(length=100), nullable=False),
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('trip_price', sa.Integer(), nullable=False),
    sa.Column('image_company', sa.String(length=100), nullable=False),
    sa.Column('image_location', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', name='planstatus'), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'plan_id')
    )
    op.create_table('planes_categorias',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planes_categorias')
    op.drop_table('favorites')
    op.drop_table('plans')
    op.drop_table('users')
    op.drop_table('token_blocked_list')
    op.drop_table('categories')
    # ### end Alembic commands ###
